services:
  - type: web
    name: batchbay
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: EBAY_CLIENT_ID
        sync: false
      - key: EBAY_CLIENT_SECRET
        sync: false
      - key: EBAY_REDIRECT_URI
        sync: false